apiVersion: v1
kind: Pod
metadata:
  name: nodepool-demo-gpu
spec:
  containers:
  - image: nginx:1.15.9
    name: nodepool-demo-gpu
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 2G
  tolerations:
  - key: "sku"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"